### ISSUE TITLE
Adding receiving_hei_id parameter to request parameters and making it required

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-omobility-cnr#2]
Hi,

It is definitely clear that the receiving hei_id is the owner of the listener CNR called by sending HEI.

However, this is clear only if the receiving hei has and uses its EWP implementation modules under its own domain name.

And in other cases and implementations as below, the receiving hei id becomes undetectable and we think it deserves its own parameter as required parameter in the URL.

Please check the scenarios below:

CASE 1 (no problem)
-----------------------------------------------------
Sending HEI ID: A =>aa.edu
Receiving HEI ID: B => bb.edu
Receiving HEI has EWP API URLs under bb.edu
=> Receiving HEI ID is clear and not needed as the CNR is sent directly to an address responsible only for a single HEI.

CASE 2 (problem detecting the receiving HEI)
-----------------------------------------------------
Sending HEI ID: A =>aa.edu
Receiving HEI ID: B => bb.edu

Receiving HEI is using an EWP provider/gateway: (domain: ewp-provider-gateway.xyz) and its EWP API URLs are under ewp-provider-gateway.xyz such as ewp-provider-gateway.xyz/omobility-cnr-listener
This provider/gateway is also responsible for some other HEIs (such as cc.edu, ff.edu, gg.edu etc)

=> In this case, the gateway/provider (ewp-provider-gateway.xyz) knows the sending hei id but cannot detect or know the receiving HEI ID and thus cannot deliver the CNR information package to the receiving HEI.

The problem here is where and to whom gateway shall deliver this CNR? bb.edu, cc.edu, ff.edu, ...?

Our suggestion is to add a receiving_hei_id parameter to request parameters and making it required.
In our opinion, this will solve such gateway delivery issues and the receiving hei ambiguities in this API as it will clearly state/define the receiving institution.

Just to make it more clear, here is a sample case from real life:

I am as A sending a cargo package to my friend B.
B is living in a single house and the house number is 17.
UPS delivers easily this cargo to number 17 as this house is a single building/house and it is owned only by B.

Secondly, I am sending a cargo package to my friend C.
C is living in a building which has 20 flats/apartments. 
UPS goes to the building for delivery but does not know definitely to whom (name?, flat/floor/apartment number?) it shoud deliver this cargo in the building.

Please let us know if we are missing anything in the API specs and docs or if there is anything not clear in my message or if details needed.

Thanks for your interest and time.
Best,

**Comment by janinamincer-daszkiewicz** [comment]
This is not the first time such suggestion is done, see https://github.com/erasmus-without-paper/ewp-specs-api-imobilities/issues/2. Generally we agree and would be happy to add such change, the only problem is backward compatibility. 
If  some more developers would support the idea, in particular developers, who are already in production with their solutions, we would make a change.
@georgschermann, @pleys and the others, whould do you think?

**Comment by georgschermann** [comment]
Our implementation currently ignores unexpected parameters and does not need the receiving_hei_id, so there is no problem for us with the change.
I checked our implementation and we are currently sending the receiving_hei_id along with the sending_hei_id as parameters on the request, and the sending_hei_id on imob cnr requests. Not sure how other implementations treat these additional parameters at the moment.

**Comment by sascoms** [comment]
Hi, 

We would like to bring this issue to the front again.

Just as a quick summary: 

We would like not only this but all of the CNRs to have both receiving and sending HEI ID parameters as required.

And maybe setting an effective date for new API versions would be motivating as well as deprecating old APIs after a while with a pre-announced effective date.

**Comment by umesh-qs** [comment]
Although our implementation does not require this, it will be good if a new parameter can be added to all the CNR APIs for those who have a single endpoint for all the HEIs they are covering.

**Comment by janinamincer-daszkiewicz** [comment]
As has been discussed during the technical workshop (October 19, 2021), none of them will be needed if there will be one manifest file per HEI.

**Comment by umesh-qs** [comment]
We at QS are discussing internally on that proposal. But since it is related as you have mentioned, can you explain a bit on how one manifest file per HEI will help?

**Comment by mkurzydlowski** [comment]
If we impose that each EWP host may cover only one HEI and we ensure that each EWP host uses different client credentials then each EWP request represents only one HEI. This way we don't need to specify it in an API parameter.

**Comment by umesh-qs** [comment]
@mkurzydlowski 
So it will be possible only if each SCHAC has a unique client certificate. Please confirm if that is what is proposed?

**Comment by mkurzydlowski** [comment]
I confirm that this is what we propose.

**Comment by umesh-qs** [comment]
@mkurzydlowski 
The issue mentioned here is about determining receiving institution. Unique client credentials will only give sending institution details. Please correct me if I am missing something.

**Comment by mkurzydlowski** [comment]
You are right, I forgot the context of your question.

Still, after changing the specs to force an EWP host to only cover one HEI, the receiver should not only know who is asking but also who is being asked. Am I right?

**Comment by umesh-qs** [comment]
@mkurzydlowski 
The receiver will anyway know who is the sender. That is not a problem at all. The problem here in "CASE 2" mentioned above is that the receiver of the CNR endpoint does not know for which HEI the CNR is.

**Comment by mkurzydlowski** [comment]
I am referring to case 2. After forcing one HEI per EWP host there will be no misconceptions about the receiver of the CNR. Every gateway/proxy will need to specify different endpoints per HEI.

**Comment by umesh-qs** [comment]
@mkurzydlowski 
Are you saying that the CNR API endpoint has to be unique for each SCHAC?

**Comment by mkurzydlowski** [comment]
Are you asking if APIs defined in different EWP hosts should be unique? I think they should but maybe that is debatable?

If they are not unique then you are right that we wouldn't know which HEI is being asked.

**Comment by umesh-qs** [comment]
@mkurzydlowski 
Ok, so the conclusion is that this issue cannot be resolved with the proposed solution of having a unique certificate per SCHAC.

**Comment by mkurzydlowski** [comment]
You are right, endpoint uniqueness is needed. Sorry for the initial confusion.

**Comment by janinamincer-daszkiewicz** [comment]
From version v5.1.0 of the https://github.com/erasmus-without-paper/ewp-specs-api-discovery no extra parameters to identify sender/receiver are needed as "A unique key is enough to identify the sender/caller, and a unique service URL (API) to identify the recipient/callee".
